name: presentation

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  domain:
    path: ../domain
  core:
    path: ../core

  # state management
  flutter_bloc: 8.1.2

  # navigation
  auto_route: ^7.1.0

  #tools

  #network
  dio: 5.1.1

  # ui

  # tools

  # ui utils

  # di
  get_it:
  injectable:

  # utils
  equatable:
  dartz: ^0.10.1
  photo_view: ^0.14.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner:
  auto_route_generator: ^7.0.0
  injectable_generator:
  freezed: ^2.3.3

flutter:
  uses-material-design: true
