name: domain

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  core:
    path: ../core
  data:
    path: ../data

  # di
  get_it:
  injectable:

  #json
  json_annotation: 4.8.0

  # utils
  equatable:
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0


dev_dependencies:
  build_runner:
  freezed: ^2.3.3
  injectable_generator:
  json_serializable: 6.6.1
